#### 1. Even Numbers:
   Write a Python program that generates a list of even numbers from 1 to 20 using list comprehension.

   Example Output: `[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]`


In [1]:
a=[i for i in range(1,21) if i%2==0]
a

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

#### 2. Squared Numbers:
   Create a Python program that generates a list of the squares of numbers from 1 to 10 using list comprehension.

   Example Output: `[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]`


In [2]:
a=[i*i for i in range(1,11)]
a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

#### 3. Vowels in a String:
   Write a Python program that takes a string as input and uses list comprehension to create a list of all the vowels in the string.

   Example Input: `"hello, world"`
   Example Output: `['e', 'o', 'o']`


In [6]:
a=input()
b=['a','e','i','o','u']
c=[i for i in a.lower() if i in b]
print(c)

hello, world
['e', 'o', 'o']


#### 4. Prime Numbers:
   Create a Python program that generates a list of prime numbers between 1 and 50 using list comprehension.

   Example Output: `[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]`


In [10]:
a=[]
for i in range(2,50):
    count=0
    for j in range(1,i):
        if i%j==0:
            count+=1
    if count<2:
        a.append(i)
print(a)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]


#### 5. Matrix Transposition:
   Implement a Python program that takes a 2D matrix (list of lists) and uses list comprehensions to compute its transpose.

   Example Input:
   ```python
   matrix = [[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]]
   ```





   Example Output:
   ```python
   transpose = [[1, 4, 7],
                [2, 5, 8],
                [3, 6, 9]]


In [11]:
import numpy as np


In [18]:
a=np.arange(1,10)
b=a.reshape(3,3)
print(f"input is {b}")
print()
print()
print(f"output is {b.T}")

input is [[1 2 3]
 [4 5 6]
 [7 8 9]]


output is [[1 4 7]
 [2 5 8]
 [3 6 9]]
